name: 'Issue comment parser'
description: 'Parse YAML or JSON from a specific issue comment'
inputs:
  github_token:
    description: 'The Github token to use for getting the issue comment via the API'
    required: true

  comment_id:
    description: 'The id of the comment to be retreived and parsed'
    required: true

  format:
    description: 'The format of the blob we expect to be parsing from the comment'
    required: true
    default: 'json'

  marker:
    description: 'The optional marker for the YAML or JSON blob to parse, in case the comment contains multiple'
    required: true
    default: ''


outputs:
  content:
    description: 'The parsed content from the comment body as a string'

runs:
  using: 'node20'
  main: 'dist/index.js'
